## Input

In [1]:
from pathlib import Path
import sys
import pandas as pd

ROOT = (Path.cwd().parent).parent
LMM_DIR = ROOT / "analysis" / "05_LMM"
sys.path.insert(0, str(LMM_DIR))

from TF_features import export_trial_features

DATA_DIR = ROOT / "data" / "05_LMM" 
BEHAVIOR_CSV = DATA_DIR / "behavior_single_trial.csv"
OUT_DIR  = ROOT / "data" / "05_LMM" / "feature"

FREQS = list(range(1, 31))

## Action binding

In [2]:
action_jobs = [
    ("PreSMAR_action_ba.csv", (0.19, 0.25), [19]),
    ("SMAR_action_ba.csv",    (0.18, 0.26), [19])
]

action_records = []
for fname, tw, excl in action_jobs:
    out_csv, merged = export_trial_features(
        csv_path=DATA_DIR / fname,
        time_window=tw,
        out_dir=OUT_DIR,
        freqs=FREQS,
        behavior_csv=BEHAVIOR_CSV,
        exclude_subjects=excl,
    )
    action_records.append({"file": fname, "time_window": tw, "out_csv": str(out_csv.relative_to(ROOT))})

pd.DataFrame(action_records)

,file,time_window,out_csv
0,PreSMAR_action_ba.csv,"(0.19, 0.25)",data\05_LMM\feature\PreSMAR_action_ba.csv
1,SMAR_action_ba.csv,"(0.18, 0.26)",data\05_LMM\feature\SMAR_action_ba.csv

## Outcome binding

In [3]:
outcome_jobs = [
    ("PostcentralL_outcome_bs.csv", (0.20, 0.30)),
    ("MTGR_outcome_bs.csv",         (0.77, 0.83)),
]

outcome_records = []
for fname, tw in outcome_jobs:
    out_csv, merged = export_trial_features(
        csv_path=DATA_DIR / fname,
        time_window=tw,
        out_dir=OUT_DIR,
        freqs=FREQS,
        behavior_csv=BEHAVIOR_CSV,
    )
    outcome_records.append({"file": fname, "time_window": tw, "out_csv": str(out_csv.relative_to(ROOT))})

pd.DataFrame(outcome_records)

,file,time_window,out_csv
0,PostcentralL_outcome_bs.csv,"(0.2, 0.3)",data\05_LMM\feature\PostcentralL_outcome_bs.csv
1,MTGR_outcome_bs.csv,"(0.77, 0.83)",data\05_LMM\feature\MTGR_outcome_bs.csv