## Input

In [1]:
from pathlib import Path
import sys
import pandas as pd

ROOT = (Path.cwd().parent).parent   
LMM_DIR = ROOT / "05_LMM"  

sys.path.insert(0, str(LMM_DIR))

from ITPC import export_angles_itpc


DATA_DIR = ROOT / "data" / "05_LMM" 
OUT_DIR  = ROOT / "data" / "05_LMM"  / "plot_data_for_itpc"

FREQS = list(range(1, 30))

## Action binding

In [2]:
# Cell 3  Action binding
action_jobs = [
    ("PreSMAR_action_ba.csv", (0.19, 0.25), [19]),
    ("SMAR_action_ba.csv",    (0.18, 0.26), [19]),
]

action_records = []
for fname, tw, excl in action_jobs:
    csv_path = DATA_DIR / fname
    angles_csv, itpc_csv, angles_df, itpc_mean_df = export_angles_itpc(
        csv_path=csv_path,
        time_window=tw,
        out_dir=OUT_DIR,
        freqs=FREQS,
        exclude_subjects=excl,
    )
    action_records.append(
         {"file": fname, "time_window": tw, "angles_csv": str(angles_csv.relative_to(ROOT)), "itpc_csv": str(itpc_csv.relative_to(ROOT))}
    )

pd.DataFrame(action_records)

,file,time_window,angles_csv,itpc_csv
0,PreSMAR_action_ba.csv,"(0.19, 0.25)",data\05_LMM\plot_data_for_itpc\PreSMAR_action_...,data\05_LMM\plot_data_for_itpc\PreSMAR_action_...
1,SMAR_action_ba.csv,"(0.18, 0.26)",data\05_LMM\plot_data_for_itpc\SMAR_action_ba_...,data\05_LMM\plot_data_for_itpc\SMAR_action_ba_...

## Outcome binding

In [3]:
outcome_jobs = [
    ("PostcentralL_outcome_bs.csv", (0.20, 0.30), []),
    ("MTGR_outcome_bs.csv",         (0.77, 0.85), []),
]

outcome_records = []
for fname, tw, excl in outcome_jobs:
    csv_path = DATA_DIR / fname
    angles_csv, itpc_csv, angles_df, itpc_mean_df = export_angles_itpc(
        csv_path=csv_path,
        time_window=tw,
        out_dir=OUT_DIR,
        freqs=FREQS,
        exclude_subjects=excl,
    )
    outcome_records.append(
        {"file": fname, "time_window": tw, "angles_csv": str(angles_csv.relative_to(ROOT)), "itpc_csv": str(itpc_csv.relative_to(ROOT))}
    )

pd.DataFrame(outcome_records)

,file,time_window,angles_csv,itpc_csv
0,PostcentralL_outcome_bs.csv,"(0.2, 0.3)",data\05_LMM\plot_data_for_itpc\PostcentralL_ou...,data\05_LMM\plot_data_for_itpc\PostcentralL_ou...
1,MTGR_outcome_bs.csv,"(0.77, 0.85)",data\05_LMM\plot_data_for_itpc\MTGR_outcome_bs...,data\05_LMM\plot_data_for_itpc\MTGR_outcome_bs...